---
prometheus_image: prom/prometheus

nodes:
# 배포한 EC2 서버의 private IP:9100 (exporter)
prometheus_node:
# 배포한 EC2 서버의 private IP:9090 (prometheus)
scrap_nodes:
# 배포한 EC2 서버의 private IP:7002 (scrap server)

prometheus_scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: "{{ prometheus_node }}"
  - job_name: 'node_exporter'
    static_configs:
    - targets: "{{ nodes }}"
  - job_name: 'scrap_exporter'
    static_configs:
    - targets: "{{ scrap_nodes }}"
